version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: class-room
    ports:
      - "3306:3306"  

    volumes:
      - ./.data:/var/lib/mysql 
