export enum EStudentReviewRole {
  NOT_ALLOW_VIEW_SCORE = 'NOT_ALLOW_VIEW_SCORE',
  VIEW_SCORE_ONLY = 'VIEW_SCORE_ONLY',
  VIEW_SCORE_AND_ANSWER = 'VIEW_SCORE_AND_ANSWER',
  VIEW_SCORE_ANSWER_SOLUTION = 'VIEW_SCORE_ANSWER_SOLUTION',
}

export enum EAttemptScore {
  FIRST_TIME = 'FIRST_TIME',
  LATEST_TIME = 'LATEST_TIME',
  HIGHEST_TIME = 'HIGHEST_TIME',
}

export enum EQuestionType {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  FILL_IN = 'FILL_IN',
}
